table 'Sales Order'
	lineageTag: a6257d88-80b5-45d4-aadb-bda4765a5fc1

	column SalesOrderLineKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 42da1c2c-8c9b-413a-9a6e-8a2aff4db2ae
		summarizeBy: none
		sourceColumn: SalesOrderLineKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Sales Order'
		dataType: string
		lineageTag: 655a9001-f9be-4e44-9e68-63273ecf7efe
		summarizeBy: none
		sourceColumn: Sales Order

		annotation SummarizationSetBy = Automatic

	column 'Sales Order Line'
		dataType: string
		lineageTag: 0eb69089-d438-40b8-9965-036d9203ebd5
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Sales Order Line
		sortByColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 63e1261b-c4c4-4778-a051-ae1c26c6d6de
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	hierarchy 'Sales Orders'
		lineageTag: 3d4600ee-8c31-4976-b423-063a4b061151

		level 'Sales Order'
			lineageTag: 283d1842-3447-44ed-9b5f-66af4d7cf4c0
			column: 'Sales Order'

		level 'Sales Order Line'
			lineageTag: c0d53e98-d236-40ee-a163-071912152d6c
			column: 'Sales Order Line'

	partition 'Sales Order-3ce1b467-3e1b-4732-b605-3e94fee75991' = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlServerInstance, SqlServerDatabase),
				    dbo_vFactSales = Source{[Schema="dbo",Item="vFactSales"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(dbo_vFactSales,{"Channel", "SalesOrderLineKey", "SalesOrderNumber", "SalesOrderLineNumber"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"SalesOrderNumber", "Sales Order"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Sales Order Line", each [Sales Order] & " - " & Text.PadStart(Number.ToText([SalesOrderLineNumber]), 2, "0")),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Sales Order Line", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"SalesOrderLineNumber"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

